### ISSUE TITLE
Error occurred while following tutorial

### ISSUE THREAD

**Issue by akgupta0777** [ikusteu/webpack_intro#1]
I need help regarding a issue I encountered during the tutorial.
I followed all the steps in the tutorial and successfully created a bundle.js minified version of index.js but when opening in the browser index.html it does not render anything.

It shows the following error on console :
```
bundle.js:2 Uncaught Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.t.render (bundle.js:2)
    at bundle.js:2
    at bundle.js:2
    at bundle.js:2
t.render @ bundle.js:2
(anonymous) @ bundle.js:2
(anonymous) @ bundle.js:2
(anonymous) @ bundle.js:2
```
What is the expected behavior : 
It should create a bundle.js file without any error and text "Hello Webpack" should be rendered.

My code that I followed along with tutorial
https://github.com/akgupta0777/webpack-learning

Please tell me where I am wrong.

Thank you

**Comment by ikusteu** [comment]
Hello, 

The solution to your error is to delete the `dist` folder and `npm run build` again.

The source of your error is that in your `index.html` file, there was `<div class="app"></div>` instead of `<div id="app"></div>`, and `index.js` looks for id="app" so it didn't know where to render.

I presume this happend if you went and edited `dist/index.html` directly. You shouldn't do that and should only edit the template in `src/index.html` and let Webpack create everything in the dist folder. This is what `html-webpack-plugin` is for.

I've cloned your repo and applied the solution and everything works fine.

If you run into any problems feel free to contact me :)

Happy Coding :)

**Comment by akgupta0777** [comment]
Thanks for the help. I will try your solution and inform you and ask for help if needed.

Thanks for your work on the common man series
It really helped me a lot. 🙂

**Comment by akgupta0777** [comment]
It worked Thanks @ikusteu
